name: "Benchmarks"
on:
  push:
  pull_request:

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "stable"
          profile: "minimal"
      - name: "Run Criterion benches"
        run: |
          cargo bench -- --save-baseline ${{ github.sha }}
      - name: "Upload Criterion results"
        uses: actions/upload-artifact@v4
        with:
          name: "criterion-results"
          path: "target/criterion"
