name: "Benchmarks"
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    bench:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: "stable"
                  profile: "minimal"
            - name: "Run Criterion benches"
              run: |
                  cargo bench --workspace
            - name: "Upload Criterion results"
              uses: actions/upload-artifact@v4
              with:
                  name: "criterion-results"
                  path: "target/criterion"
