name: Rust CI

on:
  push:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --verbose
      - name: Format Check
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --workspace
      - name: Test
        run: cargo test --verbose --all

